### ISSUE TITLE
ARM version

### ISSUE THREAD

**Issue by remidebette** [Syndlex/argo-apps-viz#1]
Hi, I have just seen this plugin pop in my krew update, nice idea.

I can't install it on my M1 mac though:
```bash
W1023 10:14:23.546167   96301 install.go:164] failed to install plugin "argo-apps-viz": plugin "argo-apps-viz" does not offer installation for this platform
failed to install some plugins: [argo-apps-viz]: plugin "argo-apps-viz" does not offer installation for this platform

```

**Comment by Syndlex** [comment]
@remidebette do you have a Krew Plugin that has Mac Binaries?

I am not familiar with Github Actions and the Go Release.
I need a plugin to look up how it works.

I have an example to build the arm linux releases. Is Kubectl using those?

**Comment by remidebette** [comment]
Hi,
So I can use for example kubectx, kubens, ktop, ksniff

https://github.com/ahmetb/kubectx/pull/217

**Comment by Syndlex** [comment]
https://github.com/kubernetes-sigs/krew-index/pull/4158/

Kubectx is not the best example :D 

you can test it from the releases. I have the Linux Version is the Version you need.

**Comment by fenio** [comment]
@Syndlex you simply have to include darwin arm64 version in this file: https://github.com/Syndlex/argo-apps-viz/blob/main/deploy/krew/plugin.yaml and with next build/release it should show up in krew index and be easily available on the Mx Macs.
I made PR for that.

**Comment by Zeratoxx** [comment]
🚀🚀
